version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
  prisma:
    image: prismagraphql/prisma:1.7
    restart: always
    ports:
      - "4466:4466"
    depends_on:
      - db
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            active: true
            host: db
            port: 3306
            user: root
            password: prisma
  client_app:
    build:
      context: client/app
      args:
        - EXPO_USERNAME
        - EXPO_PASSWORD
    ports:
      - 19000:19000
      - 19001:19001
      - "0.0.0.0:4040:4040"
    volumes:
      - yarn:/home/node/.cache/yarn
      - ./client/app:/app
      - ./client/app/package.json:/app/package.json
      - ./client/app/yarn.lock:/app/yarn.lock
      - ./tools/yarn.js:/app/yarn.js
    env_file:
      - container.env
  server_graph:
    build:
      context: server/graph
      args:
        - NODE_ENV=development
    ports:
      - 7000:4000
      - 7001:4001
    volumes:
      - yarn:/home/node/.cache/yarn
      - ./server/graph:/usr/src/app
      - ./server/graph/package.json:/usr/src/app/package.json
      - ./server/graph/yarn.lock:/usr/src/app/yarn.lock
      - ./tools/yarn.js:/usr/src/app/yarn.js
      - ~/.prisma/config.yml:/root/.prisma/config.yml
    env_file:
      - container.env
    depends_on:
      - prisma
  server_importer:
    build:
      context: server/importer
      args:
        - NODE_ENV=development
    ports:
      - 7002:7002
    volumes:
      - yarn:/home/node/.cache/yarn
      - ./server/importer:/usr/src/app
      - ./server/importer/package.json:/usr/src/app/package.json
      - ./server/importer/yarn.lock:/usr/src/app/yarn.lock
      - ./tools/yarn.js:/usr/src/app/yarn.js
    env_file:
      - container.env
    depends_on:
      - prisma

volumes:
  yarn:
